config/routes.rb
Rails.application.routes.draw do
  get 'users/index'

  root 'home#top'
  get 'top', to: 'home#top'
  get 'about', to: 'home#about'
  get 'posts/new', to: 'posts#new'
  post 'posts/create', to: 'posts#create'
  get 'posts/index', to: 'posts#index'
  get 'posts/:id', to: 'posts#show', as: :post
  get 'posts/:id/edit', to: 'posts#edit', as: :edit_post
  post 'posts/:id/update', to: 'posts#update', as: :update_post
  post 'posts/:id/destroy', to: 'posts#destroy', as: :destroy_post
  get 'login', to: 'users#login_page'
  post 'login', to: 'users#login'
  post 'logout', to: 'users#logout'
  
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    validates :content, presence: true, length: {maximum: 100}
    validates :user_id, presence: true
    
    def user
        User.find(self.user_id)
    end
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
  
  def posts
    Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_current_user
  
  def set_current_user
    @current_user = User.find(session[:user_id]) if session[:user_id]
  end
  
  def authenticate_user
    unless @current_user
      flash[:notice] = "ログインしてください"
      redirect_to login_url
    end
  end
  
  def limitation_login_user 
    if @current_user
      flash[:notice] = "すでにログイン状態です。"
      redirect_to posts_index_url
    end
  end
   

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user
  before_action :limitation_correct_user, only:[:edit, :update, :destroy]
  
  def new
    unless @current_user
      flash[:notice] = "ログインしてください"
      redirect_to login_url
    end
    @post = Post.new
  end
  
  def create
    @post = Post.new(
      content: params[:content],
      user_id: @current_user.id
    )
    if @post.save
      flash[:notice] = "投稿しました！"
      redirect_to posts_index_url
    else
      render :new
    end
  end
  
  def index
    @posts = Post.all.order(created_at: :desc)
  end
  
  def show
    @post = Post.find(params[:id])
    @user = @post.user
  end
  
  def edit
  end
  
  def update
    @post.content = params[:content]
    if @post.save
      flash[:notice] = "投稿を編集しました。"
      redirect_to posts_index_url
    else
      render :edit
    end
  end
  
  def destroy
    @post.destroy
    flash[:notice] = "投稿を削除しました。"
    redirect_to posts_index_url
  end
  
  def limitation_correct_user
    @post = Post.find(params[:id])
    unless @post.user_id == @current_user.id
      flash[:notice] = "自分以外のユーザーの投稿は編集できません。"
      redirect_to posts_index_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:index, :show, :edit, :update]
  before_action :limitation_login_user, only:[:new, :create, :login_page, :login]
  before_action :limitation_correct_user, only: [:edit, :update]
  def index
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end


  
  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      image:"default.png",
      password: params[:password],
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "ユーザーを新規登録しました！"
      redirect_to user_url @user
    else
    # 次の行にユーザー新規登録フォーム再表示の処理を記述しましょう。
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.name = params[:name]
    @user.email = params[:email]
    # if params[:image]
    #   @user.image = "user_#{@user.id}.png"
    #   File.binwrite("public/user_images/#{@user.image}", params[:image].read)
    # end
    if @user.save
    flash[:notice] = "ユーザー情報を編集しました。"
    redirect_to user_url @user
    else
      render :edit
    end
  end
  
  def login_page
  end
  
  def login
    @user = User.find_by(email: params[:email], password: params[:password])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました。"
      redirect_to posts_index_url
    else
      @error_message = "メールアドレスまたはパスワードが間違っています。"
      @email = params[:email]
      @password = params[:password]
      render :login_page
    end
  end
  
  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました。"
    redirect_to login_url
  end
  
  def limitation_correct_user
    unless @current_user.id == params[:id].to_i
      flash[:notice] = "他のユーザーの編集はできません"
      redirect_to posts_index_url
    end
  end

end

# ７.６.２がうまくいかない。updateアクションで画像の変更。（画像の送信と保存）

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<div class="about-main">
  <h2>MiniTweetとは</h2>
  <p>
    SNSアプリケーションです。
    身近に起きた出来事やその時の気持ちを投稿し、他のユーザーと楽しくシェアできます。
  </p>
  <img class="about-img" src="/about.png">
</div>

app/views/home/top.html.erb
<div class="main top-main">
  <div class="top-message">
    <h2>ミニTWEETへようこそ！</h2>
    <p>楽しく呟いて世界中と共有しよう</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniTweetApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="header-logo">
        <%= link_to "MiniTweet", root_path %>
      </div>
      <ul class="header-menus">
        <% if @current_user %>
          <li><%= link_to @current_user.name, user_path(@current_user) %></li>
          <li><%= link_to "投稿一覧", posts_index_path %></li>
          <li><%= link_to "新規投稿", posts_new_path %></li>
          <li><%= link_to "全てのユーザー", users_path %></li>
          <li><%= link_to "ログアウト", logout_path, method: :post %></li>
        <% else %>
          <li><%= link_to "MiniTweetについて", about_path %></li>
          <li><%= link_to "ユーザー新規登録", new_user_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </header>
    <% if flash[:notice] %>
      <div class="flash"><%= flash[:notice] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">投稿編集</h1>
    <%= form_tag update_post_path do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error"><%= message %></div>
          <% end %>
          <textarea name="content"><%= @post.content %></textarea>
          <input type="submit" value="保存">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="main posts-index">
  <div class="container">
    <% @posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to(post.user.name, "/users/#{post.user.id}") %>
          </div>
          <%= link_to(post.content, "/posts/#{post.id}") %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <h1 class="form-heading">新規投稿</h1>
    <%= form_tag posts_create_path do %>
      <div class="form">
        <div class="form-body">
          <% @post.errors.full_messages.each do |message| %>
            <div class="form-error"><%= message %></div>
          <% end %>
          <textarea name="content"></textarea>
          <input type="submit" value="投稿">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="main posts-show">
  <div class="container">
    <div class="posts-show-item">
      <div class="post-user-name">
        <img src="<%= "/user_images/#{@user.image}"%>">
        <%= link_to @user.name, user_path(@user) %>
      </div>
      <p><%= @post.content %><p>
      <% if @post.user_id == @current_user.id %>
      <div class="post-menus">
        <%= link_to "編集", edit_post_path(@post.id), class: "post_edit_button" %>
        <%= link_to "削除", destroy_post_path(@post.id), method: :post, class: "post_delete_button" %>
      <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">ユーザーの編集</div>
    <%= form_tag user_path, method: :patch do %>
      <div class="form users-form">
        <div class="form-body">
          <% @user.errors.full_messages.each do |message| %>
              <div class="form-error"><%= message %></div>
          <% end %>
          <%= form_tag user_path, method: :patch, multipart: true do %>
            <p>ユーザー名</p>
            <!-- 次の行にname属性を追加し、値を送信できるようにしましょう -->
            <input name="name" value="<%= @user.name %>">
            <p>メールアドレス</p>
            <!-- 次の行にname属性を追加し、値を送信できるようにしましょう -->
            <input name="email" value="<%= @user.email %>">
            <p>プロフィール画像</p>
            <input name="image" type="file">
            <input type="submit" value="保存">
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="main users-index">
  <div class="container">
    <h1 class="users-heading">全てのユーザー</h1>
    <% @users.each do |user| %>
      <div class="users-index-item">
        <div class="user-left">
          <%= image_tag "/user_images/#{user.image}" %>
        </div>
        <div class="user-right">
          <%= link_to user.name , user_path(user.id)%>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/login_page.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">ログイン</div>
    <div class="form users-form">
      <div class="form-body">
        <% if @error_message %>
          <div class="form-error"><%= @error_message %></div>
        <% end %>
        <%= form_tag login_path do %>
          <p>メールアドレス</p>
          <input name="email" value = "<%= @email %>">
          <p>パスワード</p>
          <input name="password" type="password" value = "<%= @password %>">
          <input type="submit" value="ログイン">
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <%= form_tag users_path  do %>
      <div class="form users-form">
        <div class="form-body">
          <% @user.errors.full_messages.each do |message| %>
            <div class="form-error"><%= message %></div>
          <% end %>
          <p>ユーザー名</p>
          <!-- 次の行に１行の入力フォームを作成するコードを記述しましょう。 -->
          <input name="name" value="<%= @user.name %>">
          <p>メールアドレス</p>
          <!-- 次の行に１行の入力フォームを作成するコードを記述しましょう。 -->
          <input name="email" value="<%= @user.email %>">
          <p>パスワード</p>
          <input name="password" type="password" value="<%= @user.password %>">
          <input type="submit" value="新規登録">
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="main user-show">
  <div class="container">
    <div class="user">
      <%= image_tag "/user_images/#{@user.image}" %>
      <h2><%= @user.name %></h2>
      <p><%= @user.email %></p>
      <% if @user.id == @current_user.id %>
        <%= link_to "ユーザー情報を編集する", edit_user_path(@user.id), class: "user_edit_button" %>
      <% end %>
    </div>
    <% @user.posts.each do |post| %>
      <div class="posts-index-item">
        <div class="post-left">
          <img src="<%= "/user_images/#{post.user.image}" %>">
        </div>
        <div class="post-right">
          <div class="post-user-name">
            <%= link_to post.user.name, user_path(post.user.id) %>
          </div>
          <%= link_to post.content, post_path(post.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>